baseurl: "/"
title: 쉐리샵 Release Note
theme: ghostwriter
languageCode: ko-kr
copyright: 이피엔스
pygmentsUseClasses: true
pygmentsCodefences: true

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 2

privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: false

author:
  name: 김도령
  # profile: "https://google.com/+XXX"

taxonomies:
  tag: tags

params:
  mainSections:
    - post
  intro: true
  headline: Realease Note
  description: 쉐리샵
  email: kimehfud1@epiens.com
  opengraph: true
  dateFormat: "Mon, Jan 2, 2006"
  exponeaJsUrl: ""
  exponeaTarget: ""
  exponeaToken: ""
  exponeaTrackVisits: false
  readingTime: true
  # readingTimeText: "Estimated reading time:"
  fathomUrl: ""
  fathomSiteId: ""

permalinks:
  post: "/:year/:month/:day/:filename/"

# menu:
#   main:
#     - name: 어드민
#       url: /admin
#       weight: 2
#     - name: 브랜드관
#       url: /brands/
#       weight: 3